#!/usr/bin/env node
/**
 * Freeze the route contract for PHP to verify against.
 *
 * PHP does not parse JavaScript, so `pages.mjs` — the static build's own route
 * manifest — is exported to JSON here and committed. `wp emposo verify
 * --routes` then asserts every route in it resolves to the expected object,
 * which is what makes URL preservation a test rather than an intention.
 *
 * Carries a hash of the source manifest so the check fails loudly if someone
 * edits pages.mjs without re-exporting, rather than verifying against a stale
 * contract.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { routes, STATIC_ROOT, REPO_ROOT } from './routes.mjs';

const OUT = path.join(REPO_ROOT, 'client-mu-plugins', 'emposo-core', 'data', 'routes.json');

/**
 * Which WordPress object serves a route.
 *
 * Only `/case-studies/<slug>/` is a custom post type. Everything else is a
 * Page, because the Page tree must own each URL prefix: a CPT or taxonomy
 * rewrite on `/expertise/`, `/portfolio/` or `/branchen/` would be registered
 * above the page rules and 404 the hand-authored pages that share the prefix.
 */
function objectType(route) {
	if (route.kind === '404') return 'not_found';
	if (/^case-studies\/[^/]+\/index\.html$/.test(route.out)) return 'emposo_case_study';
	return 'page';
}

/** Terminal path segment, which is the object's post_name. */
function slug(route) {
	if (route.kind === '404') return '';
	const trimmed = route.out.replace(/\/?index\.html$/, '');
	if (trimmed === '' || trimmed === 'index.html') return '';
	return trimmed.split('/').pop();
}

function hashOf(file) {
	return createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 16);
}

const contract = {
	schema: 1,
	note: 'Generated by tools/export-routes.mjs from reference/static/pages.mjs. Do not hand-edit.',
	sources: {
		'pages.mjs': hashOf(path.join(STATIC_ROOT, 'pages.mjs')),
		'content/site-data.mjs': hashOf(path.join(STATIC_ROOT, 'content', 'site-data.mjs')),
	},
	routes: routes.map((route) => ({
		url: route.url,
		slug: slug(route),
		objectType: objectType(route),
		parentPath: (() => {
			const trimmed = route.out.replace(/\/?index\.html$/, '');
			const parts = trimmed.split('/').filter(Boolean);
			return parts.length > 1 ? parts.slice(0, -1).join('/') : '';
		})(),
		title: route.title,
		description: route.description,
		bodyClass: route.bodyClass,
		scripts: route.scripts,
		nav: route.nav,
		navGroup: route.navGroup,
		navExact: route.navExact,
	})),
};

writeFileSync(OUT, `${JSON.stringify(contract, null, '\t')}\n`);

const counts = contract.routes.reduce((acc, r) => {
	acc[r.objectType] = (acc[r.objectType] ?? 0) + 1;
	return acc;
}, {});

console.log(`wrote ${path.relative(REPO_ROOT, OUT)}`);
console.log(`  ${contract.routes.length} routes:`, Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', '));
console.log(`  source hashes: ${Object.entries(contract.sources).map(([k, v]) => `${k}=${v}`).join(' ')}`);
