#!/usr/bin/env node
/**
 * Freeze the route contract for PHP to verify against.
 *
 * PHP does not parse JavaScript, so `pages.mjs` — the static build's own route
 * manifest — is exported to JSON here and committed. `wp emposo verify
 * --routes` then asserts every route in it resolves to the expected object,
 * which is what makes URL preservation a test rather than an intention.
 *
 * Carries a hash of the source manifest so the check fails loudly if someone
 * edits pages.mjs without re-exporting, rather than verifying against a stale
 * contract.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { routes, STATIC_ROOT, REPO_ROOT } from './routes.mjs';

const OUT = path.join(REPO_ROOT, 'client-mu-plugins', 'emposo-core', 'data', 'routes.json');

/**
 * Which WordPress object serves a route.
 *
 * Only `/case-studies/<slug>/` is a custom post type. Everything else is a
 * Page, because the Page tree must own each URL prefix: a CPT or taxonomy
 * rewrite on `/expertise/`, `/portfolio/` or `/branchen/` would be registered
 * above the page rules and 404 the hand-authored pages that share the prefix.
 */
function objectType(route) {
	if (route.kind === '404') return 'not_found';
	if (/^case-studies\/[^/]+\/index\.html$/.test(route.out)) return 'emposo_case_study';
	return 'page';
}

/** Terminal path segment, which is the object's post_name. */
function slug(route) {
	if (route.kind === '404') return '';
	const trimmed = route.out.replace(/\/?index\.html$/, '');
	if (trimmed === '' || trimmed === 'index.html') return '';
	return trimmed.split('/').pop();
}

/**
 * Resolve a route's body to a template kind the PHP side can act on.
 *
 * Kept here rather than in PHP so the mapping lives next to the manifest it is
 * derived from, and so a manifest shape the exporter does not understand fails
 * loudly at export time instead of rendering an empty page.
 */
function bodyFor(route) {
	const content = route.content;

	if (Array.isArray(content)) {
		/*
		 * An array may MIX directories: /portfolio/ is
		 * ['pages/portfolio.html', 'sections/07aa-faq.html'] — the FAQ belongs
		 * to the portfolio page, not the homepage. So emit each entry as a
		 * parts/-relative path rather than a bare name, or the consumer cannot
		 * tell which directory to look in.
		 */
		return {
			kind: 'parts',
			// Manifest order, not filename order: 03-models renders sixth.
			parts: content.map((file) => file.replace(/\.html$/, '')),
		};
	}

	if (typeof content !== 'string') {
		throw new Error(`Unrecognised content for ${route.out}: ${JSON.stringify(content)}`);
	}

	for (const prefix of ['project', 'industry', 'discipline']) {
		if (content.startsWith(`${prefix}:`)) {
			return { kind: prefix, slug: content.slice(prefix.length + 1) };
		}
	}

	if (content.startsWith('pages/')) {
		return { kind: 'parts', parts: [content.replace(/\.html$/, '')] };
	}

	throw new Error(`Unrecognised content for ${route.out}: ${content}`);
}

function hashOf(file) {
	return createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 16);
}

const contract = {
	schema: 1,
	note: 'Generated by tools/export-routes.mjs from reference/static/pages.mjs. Do not hand-edit.',
	sources: {
		'pages.mjs': hashOf(path.join(STATIC_ROOT, 'pages.mjs')),
		'content/site-data.mjs': hashOf(path.join(STATIC_ROOT, 'content', 'site-data.mjs')),
	},
	routes: routes.map((route) => ({
		url: route.url,
		slug: slug(route),
		objectType: objectType(route),
		parentPath: (() => {
			const trimmed = route.out.replace(/\/?index\.html$/, '');
			const parts = trimmed.split('/').filter(Boolean);
			return parts.length > 1 ? parts.slice(0, -1).join('/') : '';
		})(),
		title: route.title,
		description: route.description,
		bodyClass: route.bodyClass,
		scripts: route.scripts,
		nav: route.nav,
		navGroup: route.navGroup,
		navExact: route.navExact,

		/*
		 * How the static build produced this route's <main> content. Carried so
		 * the WordPress templates can dispatch from the same source of truth:
		 *   'pages/x.html'    -> parts/pages/x.php
		 *   [ 'sections/..' ] -> an ordered list of parts/sections/*.php
		 *   'project:slug'    -> the case-study renderer
		 *   'industry:slug'   -> the industry renderer
		 *   'discipline:slug' -> the discipline renderer
		 */
		content: route.content,
		body: bodyFor(route),
	})),
};

writeFileSync(OUT, `${JSON.stringify(contract, null, '\t')}\n`);

const counts = contract.routes.reduce((acc, r) => {
	acc[r.objectType] = (acc[r.objectType] ?? 0) + 1;
	return acc;
}, {});

console.log(`wrote ${path.relative(REPO_ROOT, OUT)}`);
console.log(`  ${contract.routes.length} routes:`, Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', '));
console.log(`  source hashes: ${Object.entries(contract.sources).map(([k, v]) => `${k}=${v}`).join(' ')}`);
